/**
 * macOS app build, notarisation, and Sparkle appcast update.
 *
 * Delegates the heavy lifting to the existing build-and-notarize.sh script.
 * After the build, commits and pushes the updated appcast.xml so that
 * Sparkle can notify existing users about the new version.
 *
 * Only available on macOS (process.platform === "darwin").
 */

import { existsSync } from "node:fs";
import path from "node:path";
import * as p from "@clack/prompts";
import pc from "picocolors";
import type { ReleaseContext } from "./types.js";
import { CommandError, handleCancel, run, runLiveCapture } from "./utils.js";

/**
 * Build the macOS app and update the Sparkle appcast feed.
 */
export async function buildMacosApp(ctx: ReleaseContext): Promise<void> {
  const { repoRoot, newMacosVersion, dryRun } = ctx;
  const macosDir = path.join(repoRoot, "apps/macos");
  const scriptPath = path.join(macosDir, "scripts/build-and-notarize.sh");
  const dmgPath = path.join(macosDir, "build/Opengram.dmg");

  if (process.platform !== "darwin") {
    p.log.warn("macOS builds can only run on macOS — skipping");
    return;
  }

  if (!existsSync(scriptPath)) {
    p.log.error(`Build script not found: ${scriptPath}`);
    return;
  }

  // ── Run the build (with retry loop) ───────────────────────────────────────

  p.log.info("Starting macOS build (this may take a while)...");
  p.log.info(
    pc.dim(
      "The build script handles: archive → sign → notarize → DMG → Sparkle",
    ),
  );

  let buildSucceeded = false;

  // Retry loop — the user can fix issues and retry without restarting
  while (!buildSucceeded) {
    if (dryRun) {
      p.log.info(
        `${pc.dim("[dry-run]")} ${pc.cyan(`bash scripts/build-and-notarize.sh`)} (in apps/macos/)`,
      );
      buildSucceeded = true;
      break;
    }

    try {
      await runLiveCapture(`bash scripts/build-and-notarize.sh`, {
        cwd: macosDir,
      });
      buildSucceeded = true;
      p.log.success("macOS build completed");
    } catch (err) {
      // Show the error clearly
      p.log.error("macOS build script exited with an error.");

      // Display the last lines of output so the error is easy to spot
      if (err instanceof CommandError && err.tail) {
        p.note(err.tail, "Last lines of build output");
      }

      // Check if the DMG was already built (build may have succeeded
      // but a later step like Sparkle signing failed)
      const dmgExists = existsSync(dmgPath);
      if (dmgExists) {
        p.log.info(
          pc.yellow(
            "The DMG was built and notarized successfully — the failure is in a later step (likely Sparkle signing).",
          ),
        );
      }

      // Let the user decide what to do
      const options = [
        {
          value: "retry" as const,
          label: "Retry",
          hint: "fix the issue first, then retry",
        },
        ...(dmgExists
          ? [
              {
                value: "continue" as const,
                label: "Continue anyway",
                hint: "DMG is ready",
              },
            ]
          : []),
        { value: "skip" as const, label: "Skip macOS release" },
        { value: "abort" as const, label: "Abort the entire release" },
      ];

      const action = await p.select({
        message: "What would you like to do?",
        options,
      });
      handleCancel(action);

      if (action === "abort") {
        p.log.error("Release aborted.");
        process.exit(1);
      }
      if (action === "skip") {
        return;
      }
      if (action === "continue") {
        // Treat as success — DMG exists, proceed with appcast + upload
        buildSucceeded = true;
      }
      // "retry" loops back to the top
    }
  }

  // ── Commit and push appcast.xml ───────────────────────────────────────────

  const appcastPath = path.join(macosDir, "appcast.xml");

  if (existsSync(appcastPath)) {
    p.log.info("Sparkle appcast.xml was generated by the build script.");
    p.log.info(
      pc.dim(
        "Committing and pushing it so existing users get the update notification.",
      ),
    );

    const appcastRelPath = "apps/macos/appcast.xml";
    run(`git add "${appcastRelPath}"`, { cwd: repoRoot, dryRun });

    // Check if there are actually changes to commit
    const hasChanges = dryRun
      ? true
      : run("git diff --cached --name-only", { cwd: repoRoot }).includes(
          "appcast.xml",
        );

    if (hasChanges) {
      run(
        `git commit -m "chore(macos): update Sparkle appcast for v${newMacosVersion ?? ctx.newVersion}"`,
        { cwd: repoRoot, dryRun },
      );
      run(`git push origin ${ctx.currentBranch}`, {
        cwd: repoRoot,
        dryRun,
      });
      p.log.success("appcast.xml committed and pushed");
    } else {
      p.log.info("appcast.xml unchanged — nothing to commit");
    }
  } else if (!dryRun) {
    p.log.warn(
      "appcast.xml was not generated. Make sure SPARKLE_EDDSA_KEY is set in apps/macos/.env.build",
    );
  }

  // ── Verify DMG exists ────────────────────────────────────────────────────

  if (existsSync(dmgPath)) {
    p.log.success(`DMG ready at: ${pc.dim(dmgPath)}`);
    p.log.info(
      pc.dim("It will be uploaded to the GitHub Release if you create one."),
    );
  }
}
